---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatgptdevopsexample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatgptdevopsexample
  template:
    metadata:
      labels:
        app: chatgptdevopsexample
    spec:
      containers:
      - name: chatgptdevopsexample
        image: mitin20/chatgpt_devops_example:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-devops-example-svc
spec:
  selector:
    app: chatgptdevopsexample
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: ClusterIP
