name: Deploy to K8s

on:
  workflow_run:
    workflows: ["Build & Push Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract short sha version for tagging
        shell: bash
        run: |
          tagVersion=$(git log -1 --pretty=%h)
          echo "short sha version for tag: $tagVersion"       
      - name: Copy KUBE_CONFIG
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: echo "${KUBE_CONFIG}" | base64 -d > kubeconfig
      - name: Deploy k8s/chatgp_devops-example.yaml
        run: |
          kubectl apply -f AIAC/k8s/chatgp_devops-example.yaml --kubeconfig=kubeconfig
          kubectl set image deployment/chatgptdevopsexample chatgptdevopsexample="mitin20/chatgpt_devops_example:0.0.$GITHUB_RUN_NUMBER" --kubeconfig=kubeconfig
