name: Deploy to K8s

on:
  workflow_run:
    workflows: ["Build & Push Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy KUBE_CONFIG
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: echo "${KUBE_CONFIG}" | base64 -d > kubeconfig
      - name: Deploy k8s/chatgp_devops-example.yaml
        run: |
          pwd
          ls -lha
          kubectl apply -f AIAC/k8s/chatgp_devops-example.yaml --kubeconfig=kubeconfig
