name: Build & Push Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:      

jobs:
  build-and-push-docker:
    name: Build and push docker
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}      
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
    - name: Extract short sha version for tagging
      shell: bash
      run: |
        Version=$(git log -1 --pretty=%h)
        echo "short sha version for tag: $Version"     
        echo ::set-output name=tagVersion::`echo ${Version}`      
    - name: Build the Dockerfile
      run: |
        cd AIAC/
        docker build -f Dockerfile . \
        -t chatgpt_devops_example:${tagVersion}
    - name: Login to Dockerhub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - name: Tag and Push Docker
      run: |
        docker tag chatgpt_devops_example:${tagVersion} $DOCKER_USERNAME/chatgpt_devops_example:${tagVersion}
        docker push $DOCKER_USERNAME/chatgpt_devops_example:${tagVersion}
